name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: ssh deploy
    - uses: easingthemes/ssh-deploy@v2.0.8
      with:
        # Private Key
        SSH_PRIVATE_KEY: 2JpdKyq2fKpPjf
        # Remote host
        REMOTE_HOST: diamondway.org
        # Remote user
        REMOTE_USER: alexk
        # Target directory
        TARGET: /var/www/vhosts/diamondway.org/httpdocs/manhattan-project/matras
